version: '3'

services:
  funder:
    build: ./funder
    environment:
      - FUND=$FUND 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - ETH_RPC_URL=$ETH_RPC_URL
      - ENTRYPOINT=$ENTRYPOINT
      - VERBOSE=$VERBOSE
    restart: on-failure:3
    depends_on:
      eth-node:
        condition: service_started

  deployer:
    build: ./deployer
    environment:
      - ETH_RPC_URL=$ETH_RPC_URL
      - ENTRYPOINT=$ENTRYPOINT
      - VERBOSE=$VERBOSE
    depends_on:
      funder:
        condition: service_completed_successfully

  eth-node:
    container_name: geth-1.14
    ports: [ '8545:8545' ]
    image: ethereum/client-go:release-1.14
    command: --verbosity 1
      --http.vhosts '*,localhost,host.docker.internal'
      --http
      --http.api eth,net,web3,debug
      --http.corsdomain '*'
      --http.addr "0.0.0.0"
      --networkid 1337
      --dev
      --dev.period 0
      --allow-insecure-unlock
      --rpc.allow-unprotected-txs
      --dev.gaslimit 20000000


